apiVersion: contextcore.io/v1
kind: ProjectContext
metadata:
  name: paymentservice-context
  namespace: online-boutique
  labels:
    app: paymentservice
    team: payments
spec:
  project:
    id: "online-boutique"
    epic: "EPIC-004"
    tasks:
      - "TASK-0051"
      - "TASK-0052"
      - "TASK-0053"

  design:
    doc: "https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/architecture.md#payment-service"
    adr: "ADR-012-mock-payment-processor"
    apiContract: "https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/protos/demo.proto"

  business:
    criticality: critical
    value: revenue-primary
    owner: payments-team
    costCenter: "CC-PAYMENTS-001"

  requirements:
    availability: "99.99"
    latencyP99: "300ms"
    errorBudget: "0.01"
    throughput: "500rps"

  risks:
    - type: security
      description: "Handles payment card data - requires PCI DSS compliance"
      priority: P1
      mitigation: "ADR-013-pci-tokenization"
    - type: financial
      description: "Transaction integrity - failed payments impact revenue"
      priority: P1
      mitigation: "ADR-006-payment-idempotency"
    - type: compliance
      description: "PCI DSS compliance required for card processing"
      priority: P1
      mitigation: "ADR-014-pci-audit-logging"

  targets:
    - kind: Deployment
      name: paymentservice
    - kind: Service
      name: paymentservice

  observability:
    traceSampling: 1.0
    metricsInterval: "10s"
    dashboardPlacement: featured
    alertChannels:
      - "payments-oncall"
      - "pagerduty-p1"
      - "security-alerts"
