"""
Central type definitions for ContextCore.

This module is the SINGLE SOURCE OF TRUTH for all status, priority, and type enums
used throughout ContextCore. All other modules should import from here to prevent
naming drift and ensure consistency.

Usage:
    from contextcore.contracts.types import TaskStatus, Priority, InsightType
"""

from __future__ import annotations

from enum import Enum


class TaskStatus(str, Enum):
    """
    Task lifecycle statuses.

    These statuses apply to tasks tracked via TaskTracker and are used
    consistently across spans, logs, and metrics.
    """

    BACKLOG = "backlog"
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    BLOCKED = "blocked"
    DONE = "done"
    CANCELLED = "cancelled"

    @classmethod
    def active_statuses(cls) -> list["TaskStatus"]:
        """Return statuses that indicate active work."""
        return [cls.TODO, cls.IN_PROGRESS, cls.IN_REVIEW, cls.BLOCKED]

    @classmethod
    def terminal_statuses(cls) -> list["TaskStatus"]:
        """Return statuses that indicate work is finished."""
        return [cls.DONE, cls.CANCELLED]


class HandoffStatus(str, Enum):
    """
    Agent handoff lifecycle statuses.

    Used for agent-to-agent task delegation tracking.
    """

    PENDING = "pending"
    ACCEPTED = "accepted"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    TIMEOUT = "timeout"

    @classmethod
    def active_statuses(cls) -> list["HandoffStatus"]:
        """Return statuses that indicate handoff is in progress."""
        return [cls.PENDING, cls.ACCEPTED, cls.IN_PROGRESS]

    @classmethod
    def terminal_statuses(cls) -> list["HandoffStatus"]:
        """Return statuses that indicate handoff is finished."""
        return [cls.COMPLETED, cls.FAILED, cls.TIMEOUT]


class SessionStatus(str, Enum):
    """
    Agent session lifecycle statuses.

    Used for tracking agent session state.
    """

    ACTIVE = "active"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class Priority(str, Enum):
    """
    Priority levels for tasks, handoffs, and questions.

    This is the canonical priority system used throughout ContextCore.
    Note: AlertPriority (P1-P4) is a separate system for alert severity.
    """

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"

    @classmethod
    def from_alert_priority(cls, alert_priority: str) -> "Priority":
        """Convert AlertPriority (P1-P4) to Priority."""
        mapping = {
            "P1": cls.CRITICAL,
            "P2": cls.HIGH,
            "P3": cls.MEDIUM,
            "P4": cls.LOW,
        }
        return mapping.get(alert_priority, cls.MEDIUM)

    def to_alert_priority(self) -> str:
        """Convert to AlertPriority (P1-P4)."""
        mapping = {
            Priority.CRITICAL: "P1",
            Priority.HIGH: "P2",
            Priority.MEDIUM: "P3",
            Priority.LOW: "P4",
        }
        return mapping[self]


class AlertPriority(str, Enum):
    """
    Alert priority levels (P1-P4 system).

    Used for alert severity classification. Maps to Priority enum.
    """

    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"


class TaskType(str, Enum):
    """Task hierarchy types."""

    EPIC = "epic"
    STORY = "story"
    TASK = "task"
    SUBTASK = "subtask"
    BUG = "bug"
    SPIKE = "spike"
    INCIDENT = "incident"


class AgentType(str, Enum):
    """
    Agent type classification.

    Used to categorize agents by their primary function.
    """

    CODE_ASSISTANT = "code_assistant"
    ORCHESTRATOR = "orchestrator"
    SPECIALIST = "specialist"
    AUTOMATION = "automation"


class InsightType(str, Enum):
    """
    Agent insight types.

    Categorizes the type of insight generated by an agent.

    Naming Convention:
        - Enum members and values use SINGULAR form (decision, not decisions)
        - Use singular form in attributes: insight_type="decision"
        - Use plural form for collections: List[InsightType], "recent_decisions"
        - Query methods may use plural in names: query_decisions(), list_blockers()

    Examples:
        # Correct - singular for attribute values
        insight = InsightData(insight_type=InsightType.DECISION.value, ...)

        # Correct - plural for collections
        decisions: List[InsightData] = querier.query(insight_type="decision")

        # Wrong - don't use plural in attribute values
        # insight_type="decisions"  # DON'T DO THIS
    """

    DECISION = "decision"
    RECOMMENDATION = "recommendation"
    BLOCKER = "blocker"
    DISCOVERY = "discovery"


class ConstraintSeverity(str, Enum):
    """Severity levels for agent constraints."""

    BLOCKING = "blocking"
    WARNING = "warning"
    ADVISORY = "advisory"


class QuestionStatus(str, Enum):
    """Status of questions for agents to answer."""

    OPEN = "open"
    ANSWERED = "answered"
    DEFERRED = "deferred"


class Criticality(str, Enum):
    """Business criticality levels."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class BusinessValue(str, Enum):
    """Business value classifications."""

    REVENUE_PRIMARY = "revenue-primary"
    REVENUE_SECONDARY = "revenue-secondary"
    COST_REDUCTION = "cost-reduction"
    COMPLIANCE = "compliance"
    ENABLER = "enabler"
    INTERNAL = "internal"


class RiskType(str, Enum):
    """Risk category types."""

    SECURITY = "security"
    COMPLIANCE = "compliance"
    DATA_INTEGRITY = "data-integrity"
    AVAILABILITY = "availability"
    FINANCIAL = "financial"
    REPUTATIONAL = "reputational"


class DashboardPlacement(str, Enum):
    """Dashboard visibility levels."""

    FEATURED = "featured"
    STANDARD = "standard"
    ARCHIVED = "archived"


class LogLevel(str, Enum):
    """Log levels."""

    DEBUG = "debug"
    INFO = "info"
    WARN = "warn"
    ERROR = "error"


class PropagationStatus(str, Enum):
    """Context propagation status at a workflow boundary."""

    PROPAGATED = "propagated"
    DEFAULTED = "defaulted"
    PARTIAL = "partial"
    FAILED = "failed"


# Convenience lists for validation
TASK_STATUS_VALUES = [s.value for s in TaskStatus]
PRIORITY_VALUES = [p.value for p in Priority]
TASK_TYPE_VALUES = [t.value for t in TaskType]
AGENT_TYPE_VALUES = [a.value for a in AgentType]
INSIGHT_TYPE_VALUES = [i.value for i in InsightType]
HANDOFF_STATUS_VALUES = [h.value for h in HandoffStatus]
SESSION_STATUS_VALUES = [s.value for s in SessionStatus]
PROPAGATION_STATUS_VALUES = [s.value for s in PropagationStatus]
