"""Script templates for ContextCore installation."""

from datetime import datetime
from typing import Optional

__all__ = ["render_docker_compose_script", "render_kind_script", "render_custom_script"]


DOCKER_COMPOSE_TEMPLATE = '''#!/bin/bash
# ContextCore Installation Script
# Generated: {timestamp}
# Method: Docker Compose
set -e

echo "=== ContextCore Installation ==="
echo "Generated by: contextcore tui script-generator"
echo ""

# Configuration
PROJECT_DIR="{project_dir}"
VENV_PATH="{venv_path}"
{env_exports}
# Navigate to project
cd "$PROJECT_DIR"

# Create virtual environment if needed
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi

# Activate virtual environment
source "$VENV_PATH/bin/activate"

# Install ContextCore
echo "Installing ContextCore..."
pip install -e ".[dev]"

# Deploy observability stack
echo "Deploying observability stack..."
make full-setup

# Verify installation
echo "Verifying installation..."
contextcore install verify

echo ""
echo "=== Installation Complete ==="
echo "Dashboard: ${{GRAFANA_URL:-http://localhost:3000}}/d/contextcore-installation"
'''


KIND_TEMPLATE = '''#!/bin/bash
# ContextCore Installation Script
# Generated: {timestamp}
# Method: Kind Cluster
set -e

echo "=== ContextCore Installation (Kind) ==="
echo "Generated by: contextcore tui script-generator"
echo ""

# Configuration
PROJECT_DIR="{project_dir}"
DEPLOY_DIR="{deploy_dir}"
VENV_PATH="{venv_path}"
CLUSTER_NAME="{cluster_name}"
{env_exports}
# Check for kind
if ! command -v kind &> /dev/null; then
    echo "Error: kind not found. Please install kind first."
    echo "See: https://kind.sigs.k8s.io/docs/user/quick-start/#installation"
    exit 1
fi

# Create Kind cluster if it doesn't exist
if ! kind get clusters | grep -q "^$CLUSTER_NAME$"; then
    echo "Creating Kind cluster: $CLUSTER_NAME"
    kind create cluster --name "$CLUSTER_NAME"
else
    echo "Kind cluster '$CLUSTER_NAME' already exists"
fi

# Set kubectl context
kubectl cluster-info --context "kind-$CLUSTER_NAME"

# Install ContextCore CLI
cd "$PROJECT_DIR"
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi
source "$VENV_PATH/bin/activate"
pip install -e ".[dev]"

# Deploy observability stack to cluster
echo "Deploying observability stack to Kind cluster..."
kubectl apply -k k8s/observability/ || echo "Note: k8s manifests may need customization"

# Wait for services
echo "Waiting for services to be ready..."
kubectl wait --for=condition=ready pod -l app=grafana --timeout=120s || true

# Verify installation
echo "Verifying installation..."
contextcore install verify --endpoint localhost:4317

echo ""
echo "=== Installation Complete ==="
echo "Dashboard: http://localhost:3000/d/contextcore-installation"
echo "Note: You may need to port-forward Grafana: kubectl port-forward svc/grafana 3000:3000"
'''


CUSTOM_TEMPLATE = '''#!/bin/bash
# ContextCore Installation Script
# Generated: {timestamp}
# Method: Custom (existing infrastructure)
set -e

echo "=== ContextCore Installation (Custom) ==="
echo "Generated by: contextcore tui script-generator"
echo ""

# Configuration
PROJECT_DIR="{project_dir}"
VENV_PATH="{venv_path}"
{env_exports}
# Navigate to project
cd "$PROJECT_DIR"

# Create virtual environment if needed
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_PATH"
fi

# Activate virtual environment
source "$VENV_PATH/bin/activate"

# Install ContextCore
echo "Installing ContextCore..."
pip install -e ".[dev]"

# Verify connection to existing infrastructure
echo "Verifying connection to infrastructure..."
contextcore install verify

echo ""
echo "=== Installation Complete ==="
echo "Dashboard: ${{GRAFANA_URL:-http://localhost:3000}}/d/contextcore-installation"
echo ""
echo "Note: This script assumes your observability infrastructure is already running."
echo "Make sure the following services are accessible:"
echo "  - Grafana: $GRAFANA_URL"
echo "  - OTLP Endpoint: $OTEL_EXPORTER_OTLP_ENDPOINT"
'''


def render_docker_compose_script(
    project_dir: str = "~/Documents/dev/ContextCore",
    venv_path: str = ".venv",
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
) -> str:
    """Render Docker Compose installation script.

    Args:
        project_dir: Path to the ContextCore project directory
        venv_path: Path to virtual environment (relative to project_dir)
        grafana_url: Optional custom Grafana URL
        otel_endpoint: Optional custom OTLP endpoint

    Returns:
        Rendered bash script
    """
    env_lines = []
    if grafana_url:
        env_lines.append(f'export GRAFANA_URL="{grafana_url}"')
    if otel_endpoint:
        env_lines.append(f'export OTEL_EXPORTER_OTLP_ENDPOINT="{otel_endpoint}"')

    env_exports = '\n'.join(env_lines) + '\n' if env_lines else ''

    return DOCKER_COMPOSE_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        project_dir=project_dir,
        venv_path=venv_path,
        env_exports=env_exports,
    )


def render_kind_script(
    project_dir: str = "~/Documents/dev/ContextCore",
    deploy_dir: str = "~/Documents/Deploy",
    venv_path: str = ".venv",
    cluster_name: str = "o11y-dev",
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
) -> str:
    """Render Kind cluster installation script.

    Args:
        project_dir: Path to the ContextCore project directory
        deploy_dir: Path to deployment directory (for cluster scripts)
        venv_path: Path to virtual environment (relative to project_dir)
        cluster_name: Name for the Kind cluster
        grafana_url: Optional custom Grafana URL
        otel_endpoint: Optional custom OTLP endpoint

    Returns:
        Rendered bash script
    """
    env_lines = []
    if grafana_url:
        env_lines.append(f'export GRAFANA_URL="{grafana_url}"')
    if otel_endpoint:
        env_lines.append(f'export OTEL_EXPORTER_OTLP_ENDPOINT="{otel_endpoint}"')

    env_exports = '\n'.join(env_lines) + '\n' if env_lines else ''

    return KIND_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        project_dir=project_dir,
        deploy_dir=deploy_dir,
        venv_path=venv_path,
        cluster_name=cluster_name,
        env_exports=env_exports,
    )


def render_custom_script(
    project_dir: str = "~/Documents/dev/ContextCore",
    venv_path: str = ".venv",
    grafana_url: Optional[str] = None,
    otel_endpoint: Optional[str] = None,
) -> str:
    """Render custom infrastructure installation script.

    Args:
        project_dir: Path to the ContextCore project directory
        venv_path: Path to virtual environment (relative to project_dir)
        grafana_url: Optional custom Grafana URL
        otel_endpoint: Optional custom OTLP endpoint

    Returns:
        Rendered bash script
    """
    env_lines = []
    if grafana_url:
        env_lines.append(f'export GRAFANA_URL="{grafana_url}"')
    else:
        env_lines.append('export GRAFANA_URL="http://localhost:3000"')
    if otel_endpoint:
        env_lines.append(f'export OTEL_EXPORTER_OTLP_ENDPOINT="{otel_endpoint}"')
    else:
        env_lines.append('export OTEL_EXPORTER_OTLP_ENDPOINT="localhost:4317"')

    env_exports = '\n'.join(env_lines) + '\n' if env_lines else ''

    return CUSTOM_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        project_dir=project_dir,
        venv_path=venv_path,
        env_exports=env_exports,
    )
