# .contextcore.yaml (Example Context Manifest v1.1)
# This file is the Master Source of Truth for the checkout-service.
# It contains BOTH the operational config (for K8s) and strategic context (for Humans/LLMs).
#
# Schema v1.1 introduces:
# - K8s-like apiVersion/kind/metadata structure
# - Structured key_results for objectives (with legacy metric/target support)
# - TacticStatus enum (planned, in_progress, blocked, in_review, done, cancelled)
# - Lifecycle fields for tactics (dates, progress, blocked_reason)
# - Artifact linkage for tactics (PRs, issues, deployments)
# - Enhanced insights (severity, expiry, evidence, recommended_actions)
# - Cross-reference validation (objectives ↔ strategies ↔ risks)

apiVersion: contextcore.io/v1alpha1
kind: ContextManifest

# ============================================================================
# METADATA
# ============================================================================
metadata:
  name: checkout-service
  owners:
    - team: checkout-squad
      slack: "#checkout-dev"
      email: checkout@company.com
  changelog:
    - date: "2026-02-05"
      version: "1.1.0"
      actor: human:neil
      summary: "Upgraded to v1.1 schema with structured metrics and lifecycle tracking"
    - date: "2026-01-28"
      version: "1.0.0"
      actor: agent:claude-code
      summary: "Initial manifest creation"
  links:
    repo: "https://github.com/company/checkout-service"
    wiki: "https://wiki.company.com/checkout"
    dashboard: "https://grafana.company.com/d/checkout"

version: "1.1"

# ============================================================================
# 1. STRATEGIC CONTEXT (Objectives, Strategies, Tactics)
#    This section drives PM tools, LLM reasoning, and roadmap planning.
#    It is NOT synced to the K8s cluster directly.
# ============================================================================

objectives:
  - id: OBJ-RELIABILITY
    description: "Achieve 99.99% availability for Black Friday"
    # Legacy fields (still supported)
    metric: availability
    target: "99.99%"
    # New structured approach (recommended)
    keyResults:
      - metricKey: availability
        unit: "%"
        target: 99.99
        targetOperator: gte  # Higher is better (≥99.99%)
        baseline: 99.95
        window: "30d"
        dataSource: "promql:avg_over_time(up{service='checkout'}[30d])"

  - id: OBJ-CONVERSION
    description: "Increase checkout conversion rate by reducing latency"
    metric: p99_latency
    target: "<200ms"
    keyResults:
      - metricKey: latency.p99
        unit: ms
        target: 200
        targetOperator: lte  # Lower is better (≤200ms)
        baseline: 350
        window: "7d"
        dataSource: "promql:histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))"

strategies:
  - id: STRAT-ASYNC
    horizon: now
    description: "Move to asynchronous processing for payment verification"
    rationale: "Synchronous calls to PaymentProviderX are the primary cause of latency spikes."
    objectiveRefs:
      - OBJ-RELIABILITY
      - OBJ-CONVERSION
    tactics:
      - id: TAC-QUEUE
        description: "Implement Kafka queue for payment events"
        status: in_progress
        owner: backend-team
        startDate: "2026-01-15T00:00:00Z"
        dueDate: "2026-02-28T00:00:00Z"
        progress: 65.0
        artifacts:
          - type: pr
            id: "123"
            url: "https://github.com/company/checkout-service/pull/123"
            title: "Add Kafka producer for payment events"
          - type: issue
            id: "CHECKOUT-456"
            url: "https://jira.company.com/browse/CHECKOUT-456"
            title: "Implement async payment processing"

      - id: TAC-RETRY
        description: "Implement exponential backoff for payment retries"
        status: planned
        owner: backend-team
        dueDate: "2026-03-15T00:00:00Z"

# ============================================================================
# 2. DERIVED INSIGHTS (Automated signals)
#    Generated by scanners or agents. Useful for "context-aware" answers.
# ============================================================================

insights:
  - id: INS-001
    type: pattern
    summary: "Heavy usage of synchronous HTTP calls detected in critical path"
    confidence: 0.95
    source: "scanner:contextcore-fox"
    severity: high
    observedAt: "2026-01-20T10:30:00Z"
    expiresAt: "2026-03-20T10:30:00Z"
    impact: "Contributes to P99 latency spikes during peak traffic"
    evidence:
      - type: file
        ref: "src/payment/client.py:42-68"
        description: "Synchronous requests.get() in payment flow"
    recommendedActions:
      - "Replace synchronous HTTP calls with async client"
      - "Consider circuit breaker pattern for external calls"

  - id: INS-002
    type: risk
    summary: "Dependency 'payment-sdk-v1' is deprecated, EOL in 90 days"
    confidence: 1.0
    source: "scanner:dependency-check"
    severity: critical
    observedAt: "2026-01-25T08:00:00Z"
    expiresAt: "2026-04-25T08:00:00Z"
    impact: "No security patches after EOL, potential compliance issues"
    evidence:
      - type: url
        ref: "https://github.com/payment-sdk/releases"
        description: "Deprecation notice in release notes"
    recommendedActions:
      - "Upgrade to payment-sdk-v2"
      - "Review migration guide at https://docs.payment-sdk.com/v2-migration"

# ============================================================================
# 3. OPERATIONAL SPEC (The K8s CRD Source)
#    This section IS synced to the K8s cluster as a ProjectContext CRD.
# ============================================================================

spec:
  project:
    id: checkout-service
    epic: EPIC-101

  business:
    criticality: critical
    value: revenue-primary
    owner: checkout-team

  requirements:
    availability: "99.99"
    latencyP99: 200ms

  targets:
    - kind: Deployment
      name: checkout-v1

  observability:
    traceSampling: 1.0  # Critical service gets 100% sampling
    alertChannels:
      - pagerduty-critical

  risks:
    - type: availability
      priority: P1
      description: "Payment Gateway latency spikes during high traffic"
      mitigation: STRAT-ASYNC  # Links back to strategy!
