# Kind cluster configuration for ContextCore demo
# Includes port mappings for accessing services locally
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: contextcore-demo
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Frontend (Online Boutique)
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Grafana
      - containerPort: 30090
        hostPort: 3000
        protocol: TCP
      # OTLP gRPC (Tempo/Alloy)
      - containerPort: 30317
        hostPort: 4317
        protocol: TCP
      # OTLP HTTP (Tempo/Alloy)
      - containerPort: 30318
        hostPort: 4318
        protocol: TCP
      # Prometheus
      - containerPort: 30909
        hostPort: 9090
        protocol: TCP
